on:
  push:
    branches: main
  pull_request:
    branches: main
  merge_group:

name: ci

jobs:
  ci:
    uses: cynkra/blockr.ci/.github/workflows/ci.yaml@main
    with:
      default-deps: |
        cynkra/g6R
    secrets: inherit
    permissions:
      contents: write
